export const allExercises = [
    { name: 'Arnold Press', fields: ['weight', 'reps'], code: 'BB', tags: ['push', 'upper'] },
    { name: 'Assault Bike', fields: ['time', 'distance'], code: 'CK', tags: ['cardio', 'full-body'] },
    { name: 'Barbell Row', fields: ['weight', 'reps'], code: 'BW', tags: ['pull', 'upper'] },
    { name: 'Battle Ropes', fields: ['time'], code: 'CF', tags: ['cardio', 'upper', 'conditioning'] },
    { name: 'Bear Crawls', fields: ['time'], code: 'BH', tags: ['core', 'full-body', 'body-weight'] },
    { name: 'Bench Press', fields: ['weight', 'reps'], code: 'AC', tags: ['push', 'upper'] },
    { name: 'Bicep Curl', fields: ['weight', 'reps'], code: 'AF', tags: ['pull', 'upper'] },
    { name: 'Box Jumps', fields: ['reps'], code: 'BI', tags: ['lower', 'explosive', 'body-weight'] },
    { name: 'Burpees', fields: ['reps'], code: 'AQ', tags: ['cardio', 'full-body', 'body-weight'] },
    { name: 'Cable Chest Fly', fields: ['weight', 'reps'], code: 'BP', tags: ['push', 'upper'] },
    { name: 'Cable Lateral Raise', fields: ['weight', 'reps'], code: 'CB', tags: ['upper', 'shoulders'] },
    { name: 'Cable Rows', fields: ['weight', 'reps'], code: 'BA', tags: ['pull', 'upper'] },
    { name: 'Calf Raises', fields: ['weight', 'reps'], code: 'AN', tags: ['lower'] },
    { name: 'Chest Press (Machine)', fields: ['weight', 'reps'], code: 'BM', tags: ['push', 'upper'] },
    { name: 'Close-Grip Bench Press', fields: ['weight', 'reps'], code: 'BV', tags: ['push', 'upper'] },
    { name: 'Crunches', fields: ['reps'], code: 'AS', tags: ['core', 'body-weight'] },
    { name: 'Cycling', fields: ['time', 'distance'], code: 'AX', tags: ['cardio', 'lower'] },
    { name: 'Deadlift', fields: ['weight', 'reps'], code: 'AE', tags: ['pull', 'lower'] },
    { name: 'Decline Bench Press', fields: ['weight', 'reps'], code: 'BL', tags: ['push', 'upper'] },
    { name: 'Dumbbell Flyes', fields: ['weight', 'reps'], code: 'AL', tags: ['push', 'upper'] },
    { name: 'Dumbbell Shrugs', fields: ['weight', 'reps'], code: 'CD', tags: ['upper', 'traps'] },
    { name: 'Elliptical', fields: ['time', 'distance'], code: 'CH', tags: ['cardio'] },
    { name: 'Face Pulls', fields: ['weight', 'reps'], code: 'BC', tags: ['pull', 'upper', 'shoulders'] },
    { name: 'Farmer’s Walk', fields: ['weight', 'time'], code: 'AV', tags: ['grip', 'core', 'full-body'] },
    { name: 'Hack Squat (Machine)', fields: ['weight', 'reps'], code: 'CA', tags: ['lower'] },
    { name: 'Hammer Curl', fields: ['weight', 'reps'], code: 'BR', tags: ['pull', 'upper', 'biceps'] },
    { name: 'Hanging Leg Raises', fields: ['reps'], code: 'BF', tags: ['core', 'body-weight'] },
    { name: 'Hip Thrusts', fields: ['weight', 'reps'], code: 'AZ', tags: ['lower', 'glutes'] },
    { name: 'Incline Bench Press', fields: ['weight', 'reps'], code: 'BK', tags: ['push', 'upper'] },
    { name: 'Jump Rope', fields: ['time'], code: 'AY', tags: ['cardio', 'coordination', 'body-weight'] },
    { name: 'Jumping Jacks', fields: ['reps'], code: 'AG', tags: ['cardio', 'body-weight'] },
    { name: 'Kettlebell Swings', fields: ['weight', 'reps'], code: 'AU', tags: ['full-body', 'cardio'] },
    { name: 'Lat Pulldown', fields: ['weight', 'reps'], code: 'AK', tags: ['pull', 'upper'] },
    { name: 'Leg Curl (Machine)', fields: ['weight', 'reps'], code: 'BN', tags: ['lower', 'hamstrings'] },
    { name: 'Leg Extension (Machine)', fields: ['weight', 'reps'], code: 'BO', tags: ['lower', 'quads'] },
    { name: 'Leg Press', fields: ['weight', 'reps'], code: 'AM', tags: ['lower'] },
    { name: 'Lunges', fields: ['weight', 'reps'], code: 'AH', tags: ['lower'] },
    { name: 'Mountain Climbers', fields: ['reps'], code: 'AP', tags: ['cardio', 'core', 'body-weight'] },
    { name: 'Overhead Press', fields: ['weight', 'reps'], code: 'AJ', tags: ['push', 'upper'] },
    { name: 'Pendlay Row', fields: ['weight', 'reps'], code: 'BX', tags: ['pull', 'upper'] },
    { name: 'Plank', fields: ['weight', 'time'], code: 'AB', tags: ['core', 'body-weight'] },
    { name: 'Preacher Curl', fields: ['weight', 'reps'], code: 'BS', tags: ['pull', 'upper', 'biceps'] },
    { name: 'Pull-ups', fields: ['reps'], code: 'AI', tags: ['pull', 'upper', 'body-weight'] },
    { name: 'Push-ups', fields: ['reps'], code: 'AA', tags: ['push', 'upper', 'body-weight'] },
    { name: 'Reverse Fly', fields: ['weight', 'reps'], code: 'BQ', tags: ['pull', 'upper', 'rear-delts'] },
    { name: 'Run', fields: ['time', 'distance'], code: 'CR', tags: ['pull', 'upper', 'rear-delts'] },
    { name: 'Rowing Machine', fields: ['time', 'distance'], code: 'AW', tags: ['cardio', 'full-body'] },
    { name: 'Russian Twists', fields: ['reps', 'weight'], code: 'AO', tags: ['core', 'body-weight'] },
    { name: 'Scissor Kicks', fields: ['reps'], code: 'CP', tags: ['core', 'body-weight'] },
    { name: 'Seated Dumbbell Press', fields: ['weight', 'reps'], code: 'CC', tags: ['push', 'upper'] },
    { name: 'Side Plank', fields: ['time'], code: 'CQ', tags: ['core', 'body-weight'] },
    { name: 'Single-Leg Deadlift', fields: ['weight', 'reps'], code: 'CM', tags: ['lower', 'balance'] },
    { name: 'Sit-ups', fields: ['reps'], code: 'AR', tags: ['core', 'body-weight'] },
    { name: 'Skull Crushers', fields: ['weight', 'reps'], code: 'BU', tags: ['push', 'upper', 'triceps'] },
    { name: 'Sled Pull', fields: ['weight', 'distance'], code: 'CL', tags: ['lower', 'conditioning'] },
    { name: 'Sled Push', fields: ['weight', 'distance'], code: 'BJ', tags: ['lower', 'full-body'] },
    { name: 'Smith Machine Squat', fields: ['weight', 'reps'], code: 'BZ', tags: ['lower'] },
    { name: 'Squats', fields: ['weight', 'reps'], code: 'AD', tags: ['lower'] },
    { name: 'Stair Climber', fields: ['time', 'distance'], code: 'CI', tags: ['cardio', 'lower'] },
    { name: 'Step-ups', fields: ['weight', 'reps'], code: 'BG', tags: ['lower', 'body-weight'] },
    { name: 'Swimming', fields: ['time', 'distance'], code: 'CJ', tags: ['cardio', 'full-body'] },
    { name: 'T-Bar Row', fields: ['weight', 'reps'], code: 'BY', tags: ['pull', 'upper'] },
    { name: 'Toe Touches', fields: ['reps'], code: 'BD', tags: ['core', 'body-weight'] },
    { name: 'Tricep Dips', fields: ['reps'], code: 'AT', tags: ['push', 'upper', 'body-weight'] },
    { name: 'Treadmill Run', fields: ['time', 'distance'], code: 'CG', tags: ['cardio'] },
    { name: 'Turkish Get-Up', fields: ['weight', 'reps'], code: 'CN', tags: ['full-body', 'mobility'] },
    { name: 'Upright Row', fields: ['weight', 'reps'], code: 'CE', tags: ['pull', 'upper'] },
    { name: 'Wall Sit', fields: ['time'], code: 'BE', tags: ['lower', 'body-weight'] },
    { name: 'Windshield Wipers', fields: ['reps'], code: 'CO', tags: ['core', 'body-weight'] },
    { name: 'Zottman Curl', fields: ['weight', 'reps'], code: 'BT', tags: ['pull', 'upper', 'biceps'] }
  ];